[build]
  command = "npm run docs:build"
  publish = "docs/.next"
  ## Only build if docs or dependencies change
  ignore = "git diff --quiet $CACHED_COMMIT_REF $COMMIT_REF -- docs/ package.json package-lock.json"

[[plugins]]
  package = "@netlify/plugin-nextjs"
