services:
  - type: web
    name: gemini-subtitle-pro
    env: static
    buildCommand: git config --global url."https://github.com/".insteadOf ssh://git@github.com/ && npm install && npm run build
    staticPublishPath: ./dist
    envVars:
      - key: GEMINI_API_KEY
        sync: false
      - key: OPENAI_API_KEY
        sync: false
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
